#!/bin/env bash
options='-columns 6 -width 100 -lines 20 -bw 2 -yoffset'

selected=$(\
    cat ~/.local/share/fontawesome/icon-list \
    | rofi -dmenu -i -markup-rows \
    ${options} \
    -p "")

# exit if nothing is selected
[[ -z $selected ]] && exit

[[ -n $WAYLAND_DISPLAY ]] \
    && copy=wl-copy \
    || copy="xclip -selection clipboard"

echo -ne $(echo "$selected" |\
  awk -F';' -v RS='>' '
    NR==2{sub("&#x","",$1);print "\\u" $1;exit}'
) | $copy
