#!/bin/env bash
cd /sys/class/power_supply/BAT0/
charge="$(cat capacity)"
state="$(cat status)"

icon=""

if   [[ $charge -gt 80 ]]; then icon=""
elif [[ $charge -gt 65 ]]; then icon=""
elif [[ $charge -gt 30 ]]; then icon=""
elif [[ $charge -gt 10 ]]; then icon=""
elif [[ $charge -gt 11 ]]; then icon=""
fi

[[ $state =~ ^[Cc].* ]] && icon=""

[[ $charge == 100 ]] && charge=99

if hash dunstify &>/dev/null; then
    dunstify -r 101 "$icon  $charge"

elif hash notify-send $>/dev/null; then
    notify-send "$icon  $charge"

else 
    echo "$icon  $charge"
fi
