#!/bin/env bash
cd /sys/class/power_supply/BAT0/
charge="$(cat capacity)"
state="$(cat status)"

icon=""

if   [[ $state =~ ^[Cc].* ]]; then icon=""
elif [[ $charge >   80 ]];    then icon=""
elif [[ $charge >   65 ]];    then icon=""
elif [[ $charge >   30 ]];    then icon=""
elif [[ $charge -ge 11 ]];    then icon=""
else                               icon=""
fi

[[ $charge == 100 ]] && charge=99

if hash dunstify &>/dev/null; then
    dunstify -r 101 "$icon  $charge"

elif hash notify-send $>/dev/null; then
    notify-send "$icon  $charge"

else 
    echo "$icon  $charge"
fi
