#!/bin/bash

# Check if the script is provided with an archive file
if [ $# -eq 0 ]; then
    echo "Usage: unarc <archive_file> [output_directory]"
    exit 1
fi

archive_file="$1"
output_dir="$2"

# Check if the archive file exists
if [ ! -f "$archive_file" ]; then
    echo "unarc: $archive_file does not exist"
    exit 1
fi

# Check if the output directory is provided
if [ -z "$output_dir" ]; then
	# TODO: check if archive root is self contained
    # Extracting the first alphanumeric word
    output_dir=$(echo $archive_file | sed 's/[^[:alnum:]]/ /g'|sed 's/^ *//'|cut -d' ' -f1)
	mkdir $output_dir
fi


# Extracting archive based on file extension
case "$archive_file" in
    *.zip)
		if [ -z "$output_dir" ]; then
        	unzip -q "$archive_file" -d "$output_dir" || return 0
		else
			unzip -q "archive_file" || return 0
		fi

		if [ "$?" == 0 ]; then echo "unzip failed"; fi
		exit 1
		;;
    *.rar)
        unrar x -y "$archive_file" "$output_dir/" \
           	|| echo "unrar failed" && exit 1
        ;;
    *.tar.gz|*.tgz)
        tar xzf "$archive_file" -C "$output_dir" \
         	|| echo "tar failed" && exit 1
        ;;
    *.7z)
       	7z x "$archive_file" -o"$output_dir" \
       		|| echo "7z failed"  exit 1
        ;;
    *)
        echo "Unsupported archive format" && exit 1
        ;;
esac

echo "Done"
